MAIN_PAGE_NAME = 'Главная'
SITE_SIGN_UP_NAME = 'Регистрация'
SITE_SIGN_IN_NAME = 'Вход'
SHOW_PORTFOLIO_PAGE_NAME = 'Портфель: %s'
CREATE_PORTFOLIO_PAGE_NAME = 'Создать портфель'
COMPARE_PORTFOLIOS_PAGE_NAME = 'Сравнить портфели'
NON_CORRECT_DATA = 'Введены некорректные данные'
EVENT_INFO = "Инфо."
EVENT_ERROR = "Ошибка"
SUCCESSFUL = "Операция прошла успешно."
PAGES = [['Мой профиль', 'home']]
