# Generated by Django 3.2.7 on 2021-09-24 17:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('linked_task', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', related_query_name='user', serialize=False, to='auth.user')),
                ('avatar', models.ImageField(blank=True, default='media/user_avatars/default.jpg', null=True, upload_to='media/user_avatars/')),
                ('user_type', models.IntegerField()),
                ('user_position', models.CharField(max_length=40)),
                ('managers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[], null=True, size=None)),
                ('subordinates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[], null=True, size=None)),
                ('tasks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[], null=True, size=None)),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[], null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField()),
                ('task_status', models.IntegerField(default=0)),
            ],
        ),
    ]
